# Generated by Django 2.2.1 on 2019-07-04 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_categories', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_food', models.CharField(blank=True, max_length=200)),
                ('quantity_food', models.TextField(max_length=30, null=True)),
                ('dangers_food', models.TextField(max_length=400, null=True)),
                ('store_food', models.TextField(max_length=200, null=True)),
                ('nutri_score_food', models.CharField(max_length=30, null=True)),
                ('link_food', models.TextField(max_length=500, null=True)),
                ('img_food', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_id_foodissub', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='foodissub', to='myfoodapp.Food')),
                ('Food_id_foodsub', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='foodsub', to='myfoodapp.Food')),
                ('User_id_saved', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='foodcate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myfoodapp.Categories')),
                ('Food_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myfoodapp.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfoodapp.Question')),
            ],
        ),
    ]
